#!/usr/bin/env bash
# apply-helium.sh — generate Helium's browser chrome from the solstice palette.
#
# Helium builds its whole UI from one seed colour kept in the profile's
# Preferences (browser.theme.user_color2 + color_variant2 — exactly what its
# Settings > Appearance colour picker writes). This script translates the
# matugen-rendered palette into those prefs, so the browser follows the same
# wallpaper/preset as the shell.
#
# Helium only reads Preferences at startup, so a running instance is never
# written to: the script arms a detached watcher instead, which applies the
# latest palette as soon as Helium exits (flock-guarded, one watcher max).
#
# Wired up as the post_hook of [templates.helium] in ~/.config/matugen/config.toml
# (wallpaper engine) and called from render-everforest.py (preset themes).
set -uo pipefail

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}"
CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}"
SOLSTICE_DIR="$CONFIG_DIR/quickshell/solstice"
THEMING_JSON="$SOLSTICE_DIR/backend/config/theming_settings.json"
MATUGEN_JSON="$SOLSTICE_DIR/style/themes/matugen.json"
MATUGEN_SETTINGS="$SOLSTICE_DIR/style/themes/matugen_settings.json"
HELIUM_DIR="$CONFIG_DIR/net.imput.helium"
RENDERED="${1:-$CACHE_DIR/matugen/helium-theme.json}"
LOCK="$CACHE_DIR/solstice/helium-apply.lock"

log() { printf '[apply-helium] %s\n' "$*" >&2; }

# Application Theming toggle (templateHelium). Missing config => enabled.
if [ -f "$THEMING_JSON" ] \
   && [ "$(jq -r 'if .templateHelium == false then "off" else "on" end' "$THEMING_JSON" 2>/dev/null)" = "off" ]; then
    exit 0
fi

have_profile=false
for p in "$HELIUM_DIR"/Default "$HELIUM_DIR"/Profile*; do
    [ -f "$p/Preferences" ] && have_profile=true
done
if ! $have_profile; then
    exit 0
fi

helium_running() {
    pgrep -u "$(id -u)" -x helium >/dev/null 2>&1 && return 0
    pgrep -u "$(id -u)" -f '[/]opt/helium/helium' >/dev/null 2>&1
}

# Helium is up: arm a watcher and apply once it quits. The lock file serialises
# watchers, so rapid theme changes only ever leave one pending.
if helium_running; then
    mkdir -p "$(dirname "$LOCK")"
    (
        exec 9>"$LOCK"
        flock -n 9 || exit 0
        while helium_running; do sleep 5; done
        sleep 2
        bash "$0" "${1:-}" >/dev/null 2>&1
    ) >/dev/null 2>&1 </dev/null &
    disown 2>/dev/null || true
    log "Helium is running — palette stashed, applying on exit"
    exit 0
fi

seed="$(jq -r '.seed // empty' "$RENDERED" 2>/dev/null)"
mode="$(jq -r '.mode // empty' "$RENDERED" 2>/dev/null)"
if [ -z "$seed" ]; then
    seed="$(jq -r '.source_color // .primary // empty' "$MATUGEN_JSON" 2>/dev/null)"
    mode="$(jq -r '.mode // "dark"' "$MATUGEN_SETTINGS" 2>/dev/null)"
fi
if [ -z "$seed" ] || [ "${#seed}" -ne 7 ]; then
    log "no usable palette (seed='$seed') — skipping"
    exit 1
fi

case "$mode" in
    light) scheme=1 ;; # BrowserColorScheme::kLight
    *)     scheme=2 ;; # BrowserColorScheme::kDark
esac

# matugen scheme -> ui.mojom.BrowserColorVariant
# (kSystem=0 kTonalSpot=1 kNeutral=2 kVibrant=3 kExpressive=4)
type="$(jq -r '.type // "scheme-tonal-spot"' "$MATUGEN_SETTINGS" 2>/dev/null)"
case "$type" in
    scheme-neutral|scheme-monochrome) variant=2 ;;
    scheme-vibrant)                   variant=3 ;;
    scheme-expressive)                variant=4 ;;
    *)                                variant=1 ;;
esac

SEED="$seed" VARIANT="$variant" SCHEME="$scheme" python3 - "$HELIUM_DIR" <<'PY'
import glob, json, os, shutil, stat, sys

helium_dir = sys.argv[1]
seed = os.environ["SEED"].strip().lstrip("#")
variant = int(os.environ["VARIANT"])
scheme = int(os.environ["SCHEME"])

if len(seed) != 6:
    sys.exit("[apply-helium] bad seed colour")

r, g, b = (int(seed[i:i + 2], 16) for i in (0, 2, 4))
color = 0xFF000000 | (r << 16) | (g << 8) | b
if color >= 2 ** 31:
    color -= 2 ** 32

paths = sorted(set(
    glob.glob(os.path.join(helium_dir, "Default", "Preferences")) +
    glob.glob(os.path.join(helium_dir, "Profile*", "Preferences"))
))


def autogenerated_color(data):
    autogen = data.get("autogenerated")
    if not isinstance(autogen, dict):
        return None
    theme = autogen.get("theme")
    if not isinstance(theme, dict):
        return None
    return theme.get("color")


applied = []
for path in paths:
    try:
        with open(path) as fh:
            data = json.load(fh)
    except (OSError, ValueError) as exc:
        print(f"[apply-helium] skip {path}: {exc}", file=sys.stderr)
        continue

    theme = data.setdefault("browser", {}).setdefault("theme", {})
    ext_theme = data.setdefault("extensions", {}).setdefault("theme", {})

    if (theme.get("user_color2") == color
            and theme.get("is_grayscale2") is False
            and theme.get("color_variant2") == variant
            and theme.get("color_scheme2") == scheme
            and ext_theme.get("id") == "user_color_theme_id"
            and "pack" not in ext_theme
            and autogenerated_color(data) is None):
        continue

    theme["user_color2"] = color
    theme["is_grayscale2"] = False
    theme["color_variant2"] = variant
    theme["color_scheme2"] = scheme
    ext_theme["id"] = "user_color_theme_id"
    ext_theme.pop("pack", None)

    autogen = data.get("autogenerated")
    if isinstance(autogen, dict):
        autogen_theme = autogen.get("theme")
        if isinstance(autogen_theme, dict):
            autogen_theme.pop("color", None)
            if not autogen_theme:
                autogen.pop("theme", None)
        if not autogen:
            data.pop("autogenerated", None)

    profile = os.path.basename(os.path.dirname(path))
    backup_dir = os.path.join(helium_dir, "solstice-theme-backup")
    backup = os.path.join(backup_dir, profile + ".Preferences.original")
    try:
        if not os.path.exists(backup):
            os.makedirs(backup_dir, exist_ok=True)
            shutil.copy2(path, backup)
        tmp = path + ".solstice-tmp"
        with open(tmp, "w") as fh:
            json.dump(data, fh, separators=(",", ":"), ensure_ascii=False)
        os.chmod(tmp, stat.S_IMODE(os.stat(path).st_mode))
        os.replace(tmp, path)
    except OSError as exc:
        print(f"[apply-helium] failed to write {path}: {exc}", file=sys.stderr)
        continue
    applied.append(profile)

if applied:
    print("[apply-helium] applied to " + ", ".join(applied))
PY
