#!/usr/bin/env python3
"""generate-emoji-data.py — rebuild shell/panels/emoji_data.js.

Source: emojibase English compact dataset (MIT), the same public data the
Caelestia emoji picker is generated from. Groups/components are dropped,
entries keep [char, label, tags, group] with group pointing into `groups`.
Run after emojibase updates:

    python3 backend/scripts/generate-emoji-data.py
"""
import json
import pathlib
import urllib.request

URL = ("https://raw.githubusercontent.com/milesj/emojibase/refs/heads/"
       "master/packages/data/en/compact.raw.json")
GROUPS_URL = ("https://raw.githubusercontent.com/milesj/emojibase/refs/heads/"
              "master/packages/data/meta/groups.json")
OUT = pathlib.Path(__file__).resolve().parent.parent.parent / "shell" / "panels" / "emoji_data.js"

# Display names for the emojibase group slugs, in picker order.
GROUP_NAMES = {
    "smileys-emotion": "Smileys & Emotion",
    "people-body": "People & Body",
    "animals-nature": "Animals & Nature",
    "food-drink": "Food & Drink",
    "travel-places": "Travel & Places",
    "activities": "Activities",
    "objects": "Objects",
    "symbols": "Symbols",
    "flags": "Flags",
}


def fetch(url):
    with urllib.request.urlopen(url, timeout=60) as f:
        return json.load(f)


def main():
    groups_meta = fetch(GROUPS_URL)["groups"]
    order = []
    for idx in sorted(groups_meta, key=int):
        slug = groups_meta[idx]
        if slug in GROUP_NAMES:
            order.append((int(idx), GROUP_NAMES[slug]))
    group_of = {idx: i for i, (idx, _) in enumerate(order)}

    emojis = []
    for emoji in fetch(URL):
        g = emoji.get("group")
        if g not in group_of:
            continue
        char = emoji.get("unicode")
        label = emoji.get("label", "")
        if not char or not label:
            continue
        tags = " ".join(emoji.get("tags") or [])
        emojis.append((group_of[g], emoji.get("order", 0), char, label, tags))
    emojis.sort(key=lambda e: (e[0], e[1]))

    lines = [
        ".pragma library",
        "",
        "// Generated by backend/scripts/generate-emoji-data.py — do not edit by hand.",
        "// Source: emojibase English compact dataset (MIT). Entry format:",
        "// [char, label, tags, group index into EmojiData.groups].",
        "var groups = " + json.dumps([name for _, name in order], ensure_ascii=False),
        "",
        "var emojis = [",
    ]
    for g, _order, char, label, tags in emojis:
        lines.append("    [%s, %s, %s, %d],"
                     % (json.dumps(char, ensure_ascii=False),
                        json.dumps(label, ensure_ascii=False),
                        json.dumps(tags, ensure_ascii=False), g))
    lines.append("]")
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print("wrote %s (%d emojis, %d groups, %.1f KiB)"
          % (OUT, len(emojis), len(order), OUT.stat().st_size / 1024))


if __name__ == "__main__":
    main()
