#!/usr/bin/env python3
"""hyprland-apply.py — Hyprland appearance bridge for the solstice settings app.

The Appearance > Compositor page never edits the hand-written files under
~/.config/hypr/configs/. It owns configs/solstice.lua, which is required at
the end of ~/.config/hypr/hyprland.lua (the shell adds the require on first
apply). Values apply live through `hyprctl keyword`, so no reload is needed.

    hyprland-apply.py dump            # effective managed values as JSON
    hyprland-apply.py apply '<json>'  # rewrite solstice.lua + live keywords
"""
import json
import os
import re
import subprocess
import sys

HOME = os.path.expanduser("~")
HYPR_DIR = os.path.join(HOME, ".config", "hypr")
CONFIG_LUA = os.path.join(HYPR_DIR, "hyprland.lua")
SOLSTICE_LUA = os.path.join(HYPR_DIR, "configs", "solstice.lua")

DEFAULTS = {
    "gapsIn": 1,
    "gapsOut": 20,
    "rounding": 0,
    "borderSize": 2,
    "shadow": True,
    "shadowRange": 4,
    "animations": True,
    "panelBlur": True,
    "panelBlurAlpha": 0.38,
}

# Layer namespaces of the shell surfaces that get the frosted-panel blur.
# One hl.layer_rule per namespace (exact match, no regex) so a rename only
# ever drops one rule instead of breaking a shared pattern.
PANEL_BLUR_NAMESPACES = [
    "bar",
    "solstice-dock",
    "controlcenterpanel",
    "notificationcenter",
    "systemtray",
    "launcher",
    "audiopanel",
    "bluetoothpanel",
    "updatecenter",
    "powerpanel",
]

REQUIRE_LINE = 'pcall(require, "configs/solstice")'


def _clamp_int(v, lo, hi, fb):
    try:
        n = int(round(float(v)))
    except (TypeError, ValueError):
        return fb
    return max(lo, min(hi, n))


def _clamp_bool(v, fb):
    if isinstance(v, bool):
        return v
    if isinstance(v, str):
        low = v.strip().lower()
        if low in ("1", "true", "yes", "on"):
            return True
        if low in ("0", "false", "no", "off"):
            return False
    if isinstance(v, (int, float)):
        return bool(v)
    return fb


def _clamp_float(v, lo, hi, fb):
    try:
        n = float(v)
    except (TypeError, ValueError):
        return fb
    return max(lo, min(hi, n))


def _read(path):
    try:
        with open(path, "r", encoding="utf-8") as f:
            return f.read()
    except OSError:
        return ""


def _num(text, key):
    m = re.search(r"\b%s\s*=\s*(-?\d+(?:\.\d+)?)" % re.escape(key), text)
    if not m:
        return None
    try:
        return float(m.group(1))
    except ValueError:
        return None


def _boolean(text, key):
    m = re.search(r"\b%s\s*=\s*(true|false)" % re.escape(key), text)
    if not m:
        return None
    return m.group(1) == "true"


def _float(text, key):
    m = re.search(r"\b%s\s*=\s*(-?\d+(?:\.\d+)?)" % re.escape(key), text)
    if not m:
        return None
    try:
        return float(m.group(1))
    except ValueError:
        return None


def dump_values():
    """Effective managed values: solstice.lua wins, defaults otherwise.

    Parses exactly what render_lua writes (snake_case Lua keys, nested
    shadow/animations blocks) so a dump → apply roundtrip preserves values
    the shell did not change.
    """
    vals = dict(DEFAULTS)
    text = _read(SOLSTICE_LUA)
    if text.strip():
        for lua_key, key, lo, hi in (
            ("gaps_in", "gapsIn", 0, 100),
            ("gaps_out", "gapsOut", 0, 100),
            ("rounding", "rounding", 0, 64),
            ("border_size", "borderSize", 0, 16),
        ):
            n = _num(text, lua_key)
            if n is not None:
                vals[key] = _clamp_int(n, lo, hi, vals[key])
        m = re.search(r"shadow\s*=\s*\{[^}]*?enabled\s*=\s*(true|false)", text)
        if m:
            vals["shadow"] = m.group(1) == "true"
        m = re.search(r"shadow\s*=\s*\{[^}]*?range\s*=\s*(-?\d+(?:\.\d+)?)", text)
        if m:
            try:
                vals["shadowRange"] = _clamp_int(float(m.group(1)), 0, 100, vals["shadowRange"])
            except ValueError:
                pass
        m = re.search(r"animations\s*=\s*\{[^}]*?enabled\s*=\s*(true|false)", text)
        if m:
            vals["animations"] = m.group(1) == "true"
        # Panel blur state lives in the rendered hl.layer_rule lines
        # (blur = true/false, ignore_alpha = …): read the first rule back.
        b = _boolean(text, "blur")
        if b is not None:
            vals["panelBlur"] = b
        n = _float(text, "ignore_alpha")
        if n is not None:
            vals["panelBlurAlpha"] = max(0.0, min(1.0, n))
    return vals


def render_lua(vals):
    shadow = "true" if vals["shadow"] else "false"
    anims = "true" if vals["animations"] else "false"
    lua = (
        "-- solstice settings — generated by Appearance > Compositor. Do not edit manually.\n"
        "hl.config({\n"
        "    general = {\n"
        "        gaps_in = %(gapsIn)d,\n"
        "        gaps_out = %(gapsOut)d,\n"
        "        border_size = %(borderSize)d,\n"
        "    },\n"
        "    decoration = {\n"
        "        rounding = %(rounding)d,\n"
        "        shadow = {\n"
        "            enabled = %(shadow)s,\n"
        "            range = %(shadowRange)d,\n"
        "        },\n"
        "    },\n"
        "    animations = {\n"
        "        enabled = %(anims)s,\n"
        "    },\n"
        "})\n"
        % {
            "gapsIn": vals["gapsIn"],
            "gapsOut": vals["gapsOut"],
            "borderSize": vals["borderSize"],
            "rounding": vals["rounding"],
            "shadow": shadow,
            "shadowRange": vals["shadowRange"],
            "anims": anims,
        }
    )
    lua += render_panel_blur_lua(
        bool(vals.get("panelBlur", True)),
        float(vals.get("panelBlurAlpha", DEFAULTS["panelBlurAlpha"])),
    )
    return lua


def render_panel_blur_lua(enabled, ignore_alpha):
    """Frosted bar + panels: one blur layer rule per shell namespace.

    ignore_alpha is the transparency floor Hyprland still blurs (verified
    live: 0.3 blurs just the translucent card, 0.95 blurs the whole screen).
    Disabled renders blur = false under the same stable names so a previous
    live session's rules are neutralized instead of accumulating.
    """
    alpha = max(0.0, min(1.0, float(ignore_alpha)))
    lines = [
        "",
        "-- solstice panel blur (managed by Hyprland > Panel blur).",
        "-- Needs translucent panels (Appearance > Transparency) to be visible.",
    ]
    for ns in PANEL_BLUR_NAMESPACES:
        lines.append(
            'hl.layer_rule({ name = "solstice-blur-%s", match = { namespace = "%s" }, blur = %s, ignore_alpha = %.2f })'
            % (ns, ns, "true" if enabled else "false", alpha)
        )
    return "\n".join(lines) + "\n"


def ensure_require():
    """Wire configs/solstice.lua into hyprland.lua (append-only, idempotent)."""
    if not os.path.isfile(CONFIG_LUA):
        return False
    text = _read(CONFIG_LUA)
    if "configs/solstice" in text or "configs.solstice" in text:
        return True
    try:
        with open(CONFIG_LUA, "a", encoding="utf-8") as f:
            if text and not text.endswith("\n"):
                f.write("\n")
            f.write("\n-- solstice settings (managed by the shell)\n" + REQUIRE_LINE + "\n")
    except OSError:
        return False
    return True


def live_keywords(vals):
    """Apply values to the running compositor without a reload."""
    kws = [
        ("general:gaps_in", str(vals["gapsIn"])),
        ("general:gaps_out", str(vals["gapsOut"])),
        ("general:border_size", str(vals["borderSize"])),
        ("decoration:rounding", str(vals["rounding"])),
        ("decoration:shadow:enabled", "true" if vals["shadow"] else "false"),
        ("decoration:shadow:range", str(vals["shadowRange"])),
        ("animations:enabled", "true" if vals["animations"] else "false"),
    ]
    for key, value in kws:
        try:
            subprocess.run(["hyprctl", "keyword", key, value],
                           timeout=5, capture_output=True)
        except (OSError, subprocess.SubprocessError):
            pass
    live_panel_blur(bool(vals.get("panelBlur", True)),
                    float(vals.get("panelBlurAlpha", DEFAULTS["panelBlurAlpha"])))


def live_panel_blur(enabled, ignore_alpha):
    """Apply the panel blur layer rules to the running compositor.

    Rules cannot go through `hyprctl keyword` (Hyprland rejects it outside
    the legacy parser); they are eval'd as Lua. Same stable names as the
    managed file, so re-applying replaces instead of accumulating.
    """
    stmts = []
    for line in render_panel_blur_lua(enabled, ignore_alpha).splitlines():
        s = line.strip()
        if s.startswith("hl.layer_rule("):
            stmts.append(s)
    if not stmts:
        return
    try:
        subprocess.run(["hyprctl", "eval", "; ".join(stmts)],
                       timeout=10, capture_output=True)
    except (OSError, subprocess.SubprocessError):
        pass


def cmd_dump():
    print(json.dumps(dump_values()))


def cmd_apply(payload):
    try:
        vals = json.loads(payload)
    except (json.JSONDecodeError, TypeError):
        print(json.dumps({"ok": False, "error": "invalid JSON payload"}))
        return 1
    if not isinstance(vals, dict):
        print(json.dumps({"ok": False, "error": "payload must be an object"}))
        return 1
    cur = dump_values()
    merged = {
        "gapsIn": _clamp_int(vals.get("gapsIn", cur["gapsIn"]), 0, 100, cur["gapsIn"]),
        "gapsOut": _clamp_int(vals.get("gapsOut", cur["gapsOut"]), 0, 100, cur["gapsOut"]),
        "rounding": _clamp_int(vals.get("rounding", cur["rounding"]), 0, 64, cur["rounding"]),
        "borderSize": _clamp_int(vals.get("borderSize", cur["borderSize"]), 0, 16, cur["borderSize"]),
        "shadow": _clamp_bool(vals.get("shadow", cur["shadow"]), cur["shadow"]),
        "shadowRange": _clamp_int(vals.get("shadowRange", cur["shadowRange"]), 0, 100, cur["shadowRange"]),
        "animations": _clamp_bool(vals.get("animations", cur["animations"]), cur["animations"]),
        "panelBlur": _clamp_bool(vals.get("panelBlur", cur["panelBlur"]), cur["panelBlur"]),
        "panelBlurAlpha": _clamp_float(vals.get("panelBlurAlpha", cur["panelBlurAlpha"]), 0.0, 1.0, cur["panelBlurAlpha"]),
    }
    try:
        os.makedirs(os.path.dirname(SOLSTICE_LUA), exist_ok=True)
        with open(SOLSTICE_LUA, "w", encoding="utf-8") as f:
            f.write(render_lua(merged))
    except OSError as e:
        print(json.dumps({"ok": False, "error": "cannot write solstice.lua: %s" % e}))
        return 1
    ensure_require()
    live_keywords(merged)
    print(json.dumps({"ok": True, "values": merged}))
    return 0


def main(argv):
    if len(argv) < 2:
        print(__doc__.strip())
        return 2
    if argv[1] == "dump":
        cmd_dump()
        return 0
    if argv[1] == "apply" and len(argv) >= 3:
        return cmd_apply(argv[2])
    print(json.dumps({"ok": False, "error": "usage: dump | apply '<json>'"}))
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
